### ISSUE TITLE
Enterprise/team: user request should redirect to applicant/request tab 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4892] opened 2019-09-24 01:48 UTC
![Screenshot from 2019-09-24 07-29-51](https://user-images.githubusercontent.com/27276132/65474913-4e83c100-de9d-11e9-933f-7ddd4fd18c8a.png)
![Screenshot from 2019-09-24 07-30-03](https://user-images.githubusercontent.com/27276132/65474914-4f1c5780-de9d-11e9-9f25-b39cb0093f26.png)
right now its redirecting to landing page.. that is mission and service/plan

**Comment by paulbert** [comment] 2019-09-24 03:28
Duplicate of #4871

**Closed by paulbert** 2019-09-24 03:28 UTC
