### ISSUE TITLE
When calling same page with different parameter page does not change

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1609] opened 2018-07-10 03:38 UTC
When clicking on notification for request, from request page itself, it does not change the page content.
![sketch 74](https://user-images.githubusercontent.com/2909490/42487868-ae9f097c-8422-11e8-9a56-190e13bfa94e.png)

**Comment by paulbert** [comment] 2018-07-10 04:04
Duplicate of #1597

**Closed by paulbert** 2018-07-10 04:04 UTC
