### ISSUE TITLE
Add Resources: Dialog box fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3458] opened 2019-03-21 15:12 UTC
![Screenshot from 2019-03-21 20-55-31](https://user-images.githubusercontent.com/27276132/54762212-bff76400-4c1b-11e9-8c9f-ea4e19fbcbec.png)
-  two scrollbar is shown. One should be removed.
- Button should always be visible and fixed.
- extra space around search field

**Comment by paulbert** [comment] 2019-03-21 16:10
Duplicate of #3456

**Closed by paulbert** 2019-03-21 16:10 UTC
Labels: UI/UX
