### ISSUE TITLE
myHealth: Warning dialog message enhancement

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6417] opened 2020-05-28 13:50 UTC
It would be good if action Cancel and Ok can be Bold and Uppercase
"Click cancel to fix or click ok to submit"
![Screenshot_2020-05-28 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/83149648-10b8f580-a11a-11ea-80d9-425834781aff.png)

**Comment by paulbert** [comment] 2020-05-28 18:36
Duplicate of #6341. Closing.

**Closed by paulbert** 2020-05-28 18:36 UTC
Labels: Newbie Friendly, low priority, question
