### ISSUE TITLE
Survey title remained fixed

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2093] opened 2018-09-14 04:59 UTC
<img width="1360" alt="screenshot 2018-09-14 10 41 27" src="https://user-images.githubusercontent.com/6964191/45530545-ed95c780-b80a-11e8-85ac-c9c89912ecdf.png">

When the exams and survey tab is toggled the title should toggle as corresponding to the button clicked.
currently it remains same i.e. survey title remain fixed.

**Comment by paulbert** [comment] 2018-09-17 22:35
@yuviii This is working as intended.  Submissions is the page for exams or surveys submitted to a leader/manager to review so the title works for both.  On the `/mySurveys` endpoint the title should say Surveys and there should not be a button toggle in the upper right (issue #2067).

Closing.

**Closed by paulbert** 2018-09-17 22:35 UTC
Labels: Newbie Friendly, feature request, in progress
