### ISSUE TITLE
Team leader on member list

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4295] opened 2019-07-11 16:43 UTC
Addressed in PR #4258, not sure if this was included in previous release?

**Comment by paulbert** [comment] 2019-07-11 17:11
The issue is that for one of the teams of @Liew211 the team leader is not on top after leaving and readding.

I cannot replicate, so looking for someone else to be able to replicate.

**Comment by paulbert** [comment] 2020-06-23 17:13
Closing since this is outdated

**Closed by paulbert** 2020-06-23 17:13 UTC
Labels: qa needed
