### ISSUE TITLE
Team: new member request 

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/planet#4831] opened 2019-09-12 16:57 UTC
A member user click the 'request to join' in a team, and the admin user click 'add members' to add the user. If in this situation, the member user will appear in 'Members' and 'join requested'.

![image](https://user-images.githubusercontent.com/11765890/64804313-31bdc400-d554-11e9-87dd-c40c7250a4ca.png)
![image](https://user-images.githubusercontent.com/11765890/64804336-3d10ef80-d554-11e9-9227-65f0760e777a.png)

**Comment by paulbert** [comment] 2019-09-17 03:04
Duplicate of #4613

**Closed by paulbert** 2019-09-17 03:04 UTC
