### ISSUE TITLE
Team: Task must be editable / updatable 

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/planet#4833] opened 2019-09-13 10:54 UTC
Task must be editable / creator must be able to edit task title, description and deadline
<img width="1661" alt="Screenshot 2019-09-13 at 10 52 22 AM" src="https://user-images.githubusercontent.com/2836302/64857700-cd166e00-d614-11e9-93fe-56aa18421831.png">

**Comment by paulbert** [comment] 2019-09-13 15:42
Duplicate of #4696

**Closed by paulbert** 2019-09-13 15:42 UTC
