### ISSUE TITLE
TeamsView: use UserProfileDialog in task description

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6861] opened 2020-07-16 15:00 UTC
Click on any task which is Assigned.

![Screenshot_2020-07-16 Planet Learning](https://user-images.githubusercontent.com/45058288/87686817-b09f1100-c7a4-11ea-84ef-5a2913fc95e4.png)

Task description dialog pups us.

![Screenshot_2020-07-16 Planet Learning(1)](https://user-images.githubusercontent.com/45058288/87686956-e04e1900-c7a4-11ea-8248-a1baaad009dd.png)

When we click on Assigned to member it redirects to User Profile page. Lets use UserProfileDialog when we click on Assigned to member

**Comment by paulbert** [comment] 2020-07-16 15:43
This is actually the same dialog as clicking on the task in the calendar, so this is a duplicate of #6845

**Closed by paulbert** 2020-07-16 15:43 UTC
Labels: low priority
