### ISSUE TITLE
Submission: on empty record, Status filter for Test is set to "Not Graded"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4527] opened 2019-08-08 14:34 UTC
- By default it should be "All" for both Test and Survey
right now Status is set to "All" for Survey tab only.
![Screenshot from 2019-08-08 20-16-23](https://user-images.githubusercontent.com/27276132/62712034-cd21bd80-ba19-11e9-8faf-d029fe72bf1e.png)
![Screenshot from 2019-08-08 20-16-32](https://user-images.githubusercontent.com/27276132/62712036-cd21bd80-ba19-11e9-8192-20b59015ae08.png)

**Comment by lmmrssa** [comment] 2019-08-08 15:24
this was a feature request to show not graded submission as default view for exam

**Comment by paulbert** [comment] 2019-08-08 16:43
Working as intended, filter for tests should initialize to "Not Graded" tests because those are the most actionable items.  Closing.

**Closed by paulbert** 2019-08-08 16:43 UTC
