### ISSUE TITLE
Adding resources: error in adding resource in course update

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2400] opened 2018-10-25 15:18 UTC
<img width="738" alt="screenshot 2018-10-25 20 59 51" src="https://user-images.githubusercontent.com/6964191/47511083-2e1c4280-d899-11e8-9bcd-6376f48e63df.png">

<img width="610" alt="screenshot 2018-10-25 21 00 23" src="https://user-images.githubusercontent.com/6964191/47511088-32486000-d899-11e8-8965-13d2f9883486.png">

**Comment by paulbert** [comment] 2018-11-13 04:31
Closing since we have not reproduced since

**Closed by paulbert** 2018-11-13 04:31 UTC
Labels: priority
