### ISSUE TITLE
Teams/Enterprises: Dates not showing

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6814] opened 2020-07-14 01:24 UTC
Go to any **Teams** or **Enterprises**, select **Calendar**, the dates would not be showing after you click, you have to resize the window for the dates to show up.

### Screenshots
![Screen Shot 2020-07-13 at 9 21 00 PM](https://user-images.githubusercontent.com/57075986/87369671-12663d80-c54f-11ea-8cc2-3712f3ebf265.png)
![Screen Shot 2020-07-13 at 9 20 40 PM](https://user-images.githubusercontent.com/57075986/87369678-16925b00-c54f-11ea-9f8a-ffa42a3f3677.png)

**Comment by Haoran-Hu** [comment] 2020-07-14 02:06
It seems like it happens when a team does not have any tasks.

**Comment by paulbert** [comment] 2020-07-14 02:44
Duplicate of #4828.  I'll keep this one since that is very old and this one has some images and more description.

Note if there are any events or tasks at any point for the team the calendar will render.  There might be a simple, slightly hacky solution based on that.

**Comment by Haoran-Hu** [comment] 2020-07-15 19:20
@paulbert  Only got `ngIf="calendarTab.isActive` which is not an input attribute for rendering. Kind of confused.

**Comment by paulbert** [comment] 2020-07-16 03:32
@Haoran-Hu My point is that if the `events` array is empty in **CalendarComponent** the calendar fails to render.  We could add something to that array always like "Today" or the team/enterprise/community creation date.  It's a little bit of a hack, but is much simpler than trying to dig into https://fullcalendar.io to try to find why the rendering isn't working.

**Closed** 2020-07-17 16:23 UTC
