### ISSUE TITLE
Area between rating stars

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6269] opened 2020-05-07 14:44 UTC
![IMG_20200507_203157](https://user-images.githubusercontent.com/2909490/81308750-e2f40a00-90a1-11ea-9438-f3eb12daa3b5.jpg)
There is area between stars of rating which is very small. But even when clicking on this area popup rating and saves rating. So it is possible to end up submitting rating as 0
Shall we remove that spacing or not trigger rating in that space

**Comment by paulbert** [comment] 2020-05-08 12:46
Duplicate of #5772

**Comment by paulbert** [comment] 2020-05-12 03:40
I think if the value submitted is 0 we can not make the request to change the database?

**Comment by robinGiri** [comment] 2020-05-13 09:35
@paulbert It is possible to submit value 0 as rating in a Course or Resource if previously rating value is 0. For those Course and Resource which has got rating value its not possible to give value 0 as rating.

I have removed the margin between icons so that user can't select value 0 as rating hope this solves the problem.

**Closed** 2020-05-13 16:09 UTC
Labels: UI/UX
