### ISSUE TITLE
Enterprise Reports: Show total number

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6956] opened 2020-07-28 02:19 UTC
Show total number of Reports inside brackets besides **Reports** like **Documents** and **Applicants** ?

### Screenshot
<img width="746" alt="Screen Shot 2020-07-27 at 10 16 43 PM" src="https://user-images.githubusercontent.com/57075986/88611528-35b4e080-d057-11ea-8bfe-dddd396ed6e7.png">

**Comment by lmmrssa** [comment] 2020-07-28 02:32
duplicate of #6950

**Closed by lmmrssa** 2020-07-28 02:32 UTC
Labels: question
