### ISSUE TITLE
Feedback reply giving error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2802] opened 2018-12-20 14:41 UTC
Feedback reply is not working.
It gives the console error. Also the Re-Open/Close button of feedback detail page is not working
![screenshot from 2018-12-20 20-24-21](https://user-images.githubusercontent.com/27276132/50291060-8fc1ed00-0495-11e9-8705-f72fb0945779.png)

**Comment by paulbert** [comment] 2018-12-20 14:48
Duplicate of #2790

**Closed by paulbert** 2018-12-20 14:48 UTC
