### ISSUE TITLE
TeamsView: Margin for tab toolbar

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6501] opened 2020-06-08 20:23 UTC
In section **Teams**, select any team available,  the content in **Plan** has no blank line at the top while for **Resources**, **Courses** and **Join Requests**, there is a blank line at the top.

### Screenshots
![Screen Shot 2020-06-08 at 4 17 53 PM](https://user-images.githubusercontent.com/57075986/84076617-16c59680-a9a4-11ea-89d5-6a99c27672d0.png)
![Screen Shot 2020-06-08 at 4 18 11 PM](https://user-images.githubusercontent.com/57075986/84076623-188f5a00-a9a4-11ea-824e-1c308e97abaf.png)
![Screen Shot 2020-06-08 at 4 18 19 PM](https://user-images.githubusercontent.com/57075986/84076630-1d540e00-a9a4-11ea-8c53-f276753eabc2.png)

### Proposed Solution
Add the blank line at the top since it looks more natural.

**Comment by paulbert** [comment] 2020-06-09 03:09
Generally we should add a margin after the `mat-tab-group` toolbar so content has space in **TeamsViewComponent**.

Duplicate of #4465, but closing that one since it is so old.

**Closed** 2020-06-15 20:33 UTC
Labels: UI/UX
