### ISSUE TITLE
Course view : navigation icon on header is disabled when exam is there

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2070] opened 2018-09-11 02:50 UTC
when take exam is present in any course, the navigation icon (used to switch between steps) is disabled.
![screenshot from 2018-09-11 08-31-53](https://user-images.githubusercontent.com/27276132/45335108-858e7980-b59d-11e8-8f05-154b5ab848e3.png)

which is working fine in case where there is no exam added to steps
![screenshot from 2018-09-11 08-32-27](https://user-images.githubusercontent.com/27276132/45335122-94752c00-b59d-11e8-888a-f6878afacfaa.png)

**Comment by paulbert** [comment] 2018-09-11 03:04
This is working as intended. A member must complete the exam before moving to the next step.

**Closed** 2018-09-11 03:04 UTC
Labels: bug
