### ISSUE TITLE
Report detail: courses tab

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6511] opened 2020-06-09 02:30 UTC
Under courses tab in reports the average rating is not showing up.
![has ratings](https://user-images.githubusercontent.com/40531136/84099400-86a14480-a9d7-11ea-922d-0ac7807fb19a.png)
![courses avarage rating](https://user-images.githubusercontent.com/40531136/84099404-89039e80-a9d7-11ea-918d-ff41c2120c92.png)

**Comment by lmmrssa** [comment] 2020-06-09 02:45
looks like rating is done by admin and we are not showing anything of admin on report right now. Can you try using other user

**Comment by chtelmko** [comment] 2020-06-09 02:48
It looks like it works when rating is done by the user.

**Comment by paulbert** [comment] 2020-06-09 03:55
Closing. This is expected behavior.

**Closed by paulbert** 2020-06-09 03:55 UTC
