### ISSUE TITLE
myPlanet logs

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/planet#5800] opened 2020-02-18 03:03 UTC
Database => apk_logs
`time`
`version`
`customDeviceName`

<img width="1652" alt="Screenshot 2020-02-17 at 9 55 46 PM" src="https://user-images.githubusercontent.com/2836302/74700419-6b64bc00-51d1-11ea-8295-7ebed8e193c8.png">

**Comment by lmmrssa** [comment] 2020-02-18 03:19
related to #5798

**Comment by paulbert** [comment] 2020-02-18 04:13
Duplicate of #5798

**Closed by paulbert** 2020-02-18 04:13 UTC
