### ISSUE TITLE
Members sorting

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6884] opened 2020-07-21 01:49 UTC
Would it be better if we sort members in **Members** dialogs and lists alphabetically based on last name or userId just like the **Members** section for all the teams.

### Screenshots
<img width="1196" alt="Screen Shot 2020-07-20 at 9 34 42 PM" src="https://user-images.githubusercontent.com/57075986/88003306-90d45980-cad2-11ea-87cb-19bc8b6aa6ba.png">
<img width="977" alt="Screen Shot 2020-07-20 at 9 36 02 PM" src="https://user-images.githubusercontent.com/57075986/88003309-929e1d00-cad2-11ea-9909-15c6417e9e68.png">

**Comment by paulbert** [comment] 2020-07-30 15:41
Duplicate of #6767

**Closed by paulbert** 2020-07-30 15:41 UTC
