### ISSUE TITLE
Team: Updating and deleting team plan

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4388] opened 2019-07-23 01:23 UTC
As it is right now, it's only possible to "Add" a plan if the team was initialized without a description. I think it's a good idea to have the ability to "Update" and "Delete" a plan in case you want to keep the same people but move the team towards different goals.

**Comment by paulbert** [comment] 2019-07-23 02:49
Duplicate of #4148

**Closed by paulbert** 2019-07-23 02:49 UTC
