### ISSUE TITLE
Answer validation

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#2725] opened 2018-12-13 01:28 UTC
Currently, when a user answers questions, he/she can see if the answer is correct or not. Maybe better to remove validation when the user answers the question.

![screen shot 2018-12-10 at 3 42 39 pm](https://user-images.githubusercontent.com/35533801/49908735-e7cf7280-fe49-11e8-9570-7fbd22716375.png)

**Comment by paulbert** [comment] 2018-12-13 02:11
@svlesiv This is by design.  I think it may be revisited at a future date when we expand the ability to customize exams, but right now this is how multiple choice questions will work.  Closing for the time being.

**Closed by paulbert** 2018-12-13 02:11 UTC
Labels: question
