### ISSUE TITLE
Teams: not being able to add members using Add Members team

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4610] opened 2019-08-20 01:44 UTC
- create a team.
- click on Add members and select one or two used then hit OK button.
![Screenshot from 2019-08-20 07-27-38](https://user-images.githubusercontent.com/27276132/63310905-280dbb80-c31c-11e9-8da3-eaccb63725d3.png)

**Comment by paulbert** [comment] 2019-08-20 03:15
I can't replicate this issue, so we need to do some testing to find the cause before fixing.

**Comment by paulbert** [comment] 2019-08-20 03:20
We think it was an issue with a bad document on the `attachments` database (from the issue fixed in #4602).  Closing

**Closed by paulbert** 2019-08-20 03:20 UTC
