### ISSUE TITLE
Member Profile : Make the Back button similar to browser back button

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3195] opened 2019-02-14 15:58 UTC

**Comment by paulbert** [comment] 2019-02-14 16:38
For clarity, this back button is what needs to be changed:
![image](https://user-images.githubusercontent.com/9203229/52801991-02da8080-304d-11e9-8ec1-9fcca772d3a7.png)

**Comment by lmmrssa** [comment] 2019-02-27 01:34
Looks like it is related to https://github.com/open-learning-exchange/planet/issues/3221

**Comment by BhargaviNadendla** [comment] 2019-03-04 00:34
@paulbert I will create a pull request on this by tomorrow

**Comment by paulbert** [comment] 2019-03-07 05:17
More than related, this is a duplicate of #3221

**Closed by paulbert** 2019-03-07 05:17 UTC
Labels: in progress
