### ISSUE TITLE
Enterprise- Add Report: negative value is accepted in most of the fields

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6911] opened 2020-07-23 13:36 UTC
![Screenshot_2020-07-23 Planet Learning](https://user-images.githubusercontent.com/27276132/88292647-a12a4580-cd19-11ea-996a-7871d976f34a.png)

**Comment by paulbert** [comment] 2020-07-23 14:38
Duplicate of #6910

**Closed** 2020-07-23 14:39 UTC
