### ISSUE TITLE
Invite team members

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2256] opened 2018-10-02 02:45 UTC
<img width="1371" alt="screenshot 2018-10-02 08 19 50" src="https://user-images.githubusercontent.com/6964191/46326352-0b8d6580-c61c-11e8-8890-3c9c4fc4612b.png">

It would be better to show the invited members list as well. currently we are able to send the invitation to same user for any number of times. 

<img width="1220" alt="screenshot 2018-10-02 08 27 33" src="https://user-images.githubusercontent.com/6964191/46326577-1dbbd380-c61d-11e8-9b83-7a8d623160a3.png">

Currently every time we invite the same user it is adding the same data in table, How about like just changing the status or may be some extra flags so it will behave like its a new notification instead of adding the whole same message again.

**Comment by paulbert** [comment] 2018-10-02 03:41
Duplicate of #2188

**Closed by paulbert** 2018-10-02 03:41 UTC
Labels: enhancement, feature request, question
