### ISSUE TITLE
myHealth: Examinations should nurse who draws the vitals be indicated?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6476] opened 2020-06-04 13:41 UTC
This is similar to issue #6455.
Should the name of the nurse or the name of the lab where the vitals were taken be indicated?
![drawn by original](https://user-images.githubusercontent.com/40531136/83763975-578d7a80-a647-11ea-935d-538c59502305.png)

![drawn by](https://user-images.githubusercontent.com/40531136/83763993-5ceac500-a647-11ea-969e-c405b59ad7d4.png)

**Comment by lmmrssa** [comment] 2020-06-04 14:07
@chtelmko we are already saving the record of who did examination based on health worker profile.

**Comment by lmmrssa** [comment] 2020-06-11 16:16
Duplicate of #6515

**Closed by lmmrssa** 2020-06-11 16:16 UTC
Labels: question
