### ISSUE TITLE
Empty Achievement shows error message 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3060] opened 2019-01-30 01:28 UTC
when redirecting to Achievement page, if its empty it shows the error message.
![screenshot from 2019-01-30 07-10-54](https://user-images.githubusercontent.com/27276132/51951895-687c1980-245e-11e9-8e88-59729448aa0f.png)
 i think Empty case should show the record not found message.

**Comment by paulbert** [comment] 2019-01-30 01:31
Duplicate of #3057

**Closed by paulbert** 2019-01-30 01:31 UTC
