### ISSUE TITLE
Member's role delete issue

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5323] opened 2019-12-05 15:40 UTC
while deleting member's role using Delete icon attached inline, shows following error.
![Screenshot from 2019-12-05 21-22-17](https://user-images.githubusercontent.com/27276132/70250177-9a0ff080-17a5-11ea-8990-0e912b7c7872.png)

**Comment by paulbert** [comment] 2019-12-05 16:23
Duplicate of #5283

**Closed by paulbert** 2019-12-05 16:23 UTC
