### ISSUE TITLE
Exam Add: 'Submit Answer' Doesn't Do Anything On Last Question of Preview

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/planet#3907] opened 2019-05-28 02:48 UTC
In the exam Preview dialog box, while creating or updating an exam, the 'Submit Answer' button on the last question does not do anything. It should technically have the same functionality as 'Close Preview.' (This problem does not occur when an exam is previewed from the course view or step view page. It only occurs in the dialog box.) 

https://www.loom.com/share/fd3131f6fbe248b1a9e7712161453ec0

**Comment by paulbert** [comment] 2019-05-28 03:37
Duplicate of #3885

**Closed by paulbert** 2019-05-28 03:37 UTC
