### ISSUE TITLE
Reset button on course does not disable

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3820] opened 2019-05-16 12:58 UTC
One we filter course, then cleaning filter is not disabling the button.

**Comment by paulbert** [comment] 2019-05-16 15:03
`courses.filter` should be an empty string (`''`) when nothing is selected in the search.  If there is any value for `courses.filter` not only is the button enabled, but all of the filter functions run internally.  We should avoid this when there is nothing to filter, and make sure that on filter reset `courses.filter` is reset to an empty string.

**Comment by paulbert** [comment] 2020-03-05 15:10
Closing.  This is working as intended now.

**Closed by paulbert** 2020-03-05 15:10 UTC
