### ISSUE TITLE
Clicking next on multiple choice question is still giving error

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6053] opened 2020-03-31 01:59 UTC
![image](https://user-images.githubusercontent.com/2909490/77979311-09e15280-7324-11ea-9c28-3efdfc8fb01a.png)

**Comment by paulbert** [comment] 2020-03-31 02:18
Duplicate of #3908, but closing that issue since it is much older.

When clicking the right arrow to go to the next question in the upper right portion of the screen, one of three things will happen:

1. If the correct answer has been selected, the test will navigate to the next question
2. If the incorrect answer has been selected, the "incorrect answer" message will appear and the test will stay on the same question
3. If no answer has been selected, the spinner will pop up and never close and the above error will be in the console.

We should at least handle (3) better and navigate to the next question without error.

Later we can consider doing something different with (2), but since we only want to accept the correct answer let's leave that as is.  If the user wants to navigate to the next question they can click the arrow twice.

**Closed** 2020-04-06 19:11 UTC
