### ISSUE TITLE
Errors in clicking next arrow button in toolbar: Exams

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2747] opened 2018-12-13 15:45 UTC
I did
 - logged in through non admin
 - Created the new course
 - Clicked  new created view courses
 - take the exam
 - without answering (my first question is multiple answer multiple choice) clicked to next arrow button

<img width="734" alt="screenshot 2018-12-13 21 25 29" src="https://user-images.githubusercontent.com/6964191/49949601-1a4a9f80-ff1e-11e8-8bc8-94c8d1171337.png">

**Comment by paulbert** [comment] 2018-12-13 17:14
Duplicate of #2714

**Closed by paulbert** 2018-12-13 17:14 UTC
