### ISSUE TITLE
console error in view course

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5367] opened 2019-12-12 15:46 UTC
when course is added and try to view the course which we have there is error which says t.trim is not a function and description which we have added is not displayed.
![course](https://user-images.githubusercontent.com/45058288/70726667-8f65d600-1d26-11ea-8b4d-bb94aea0447a.PNG)

**Comment by paulbert** [comment] 2020-01-23 14:45
Now we are unable to reproduce.  Closing.

**Closed by paulbert** 2020-01-23 14:45 UTC
