### ISSUE TITLE
Error on health member list page

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6367] opened 2020-05-21 14:31 UTC
There is javascript error on health page
![image](https://user-images.githubusercontent.com/2909490/82569366-ddb5b580-9b9f-11ea-9140-f408521b9290.png)
This cause some loading image to show on health list page for examination date
![image](https://user-images.githubusercontent.com/2909490/82569397-ead2a480-9b9f-11ea-8e4f-de57d805a5c9.png)

**Comment by paulbert** [comment] 2020-05-22 03:53
Duplicate of #5284

**Comment by paulbert** [comment] 2020-05-28 05:03
@singharpita Reassigning since I think this is fixed with #6412

**Closed** 2020-05-28 08:54 UTC
Labels: bug
