### ISSUE TITLE
Exam submission submit disabled bug

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2277] opened 2018-10-04 13:46 UTC
in Submission exam,selecting any of the correct or incorrect choices is not enabling the submit button.

![screenshot from 2018-10-04 19-29-55](https://user-images.githubusercontent.com/27276132/46478189-1e668c80-c80c-11e8-9161-e9a077de2f46.png)

**Comment by singharpita** [comment] 2018-10-04 14:12
its because submitted answer is showing blank in every case.

**Comment by paulbert** [comment] 2018-10-05 01:37
Duplicate of #2262

**Closed by paulbert** 2018-10-05 01:37 UTC
Labels: bug
