### ISSUE TITLE
Course update page showing empty after console error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3899] opened 2019-05-28 01:29 UTC
added a new step and return to the course update page.
when click on submit , this console error shown and spinner keeps on loading.
![Screenshot from 2019-05-28 07-11-31](https://user-images.githubusercontent.com/27276132/58444472-2ca94600-8118-11e9-90cd-323590ca6aaa.png)
and when trying to refresh the url, course update page shows empty.
![Screenshot from 2019-05-28 07-14-37](https://user-images.githubusercontent.com/27276132/58444499-4480ca00-8118-11e9-842d-5837f467cd7e.png)

**Comment by paulbert** [comment] 2019-05-28 03:08
Duplicate of #3770

**Closed by paulbert** 2019-05-28 03:08 UTC
