### ISSUE TITLE
Notification: latest/unread one should be shown at top

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5582] opened 2020-01-21 03:06 UTC
![Screenshot from 2020-01-21 08-49-46](https://user-images.githubusercontent.com/27276132/72772078-23329800-3c2b-11ea-9444-82d51539cadd.png)

**Comment by paulbert** [comment] 2020-01-21 04:08
Closing.  This is intended behavior (bell icon has only unread and the status filter can also change this view)

**Closed by paulbert** 2020-01-21 04:08 UTC
