### ISSUE TITLE
Teams/View-Add Members

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6477] opened 2020-06-04 13:42 UTC
In Teams/View  Add members dialog, on clicking the View Profile doesn't show the profile of the member.

![Screenshot from 2020-06-04 09-36-02](https://user-images.githubusercontent.com/39105848/83764115-899edc80-a647-11ea-8871-27f022932043.png)

**Comment by lmmrssa** [comment] 2020-06-04 14:08
Duplicate of https://github.com/open-learning-exchange/planet/issues/6447

**Closed by lmmrssa** 2020-06-04 14:08 UTC
Labels: question
