### ISSUE TITLE
Notification link for community/nation news story

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5646] opened 2020-01-29 09:27 UTC
When adding story to nation, link created on notification is `/community` it needs to be change to `/`

**Comment by paulbert** [comment] 2020-01-30 15:46
Edited the title since this is not limited to nation.

The component is **CommunityComponent** which is at the `/` route and no longer at the `/community` route.

**Comment by paulbert** [comment] 2020-02-03 18:33
Duplicate of #5580

**Closed by paulbert** 2020-02-03 18:33 UTC
