### ISSUE TITLE
Updating team/enterprise from team/enterprise details page result in incomplete success message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5990] opened 2020-03-19 13:58 UTC
![Screenshot from 2020-03-19 19-41-46](https://user-images.githubusercontent.com/27276132/77075039-d6482380-6a19-11ea-9b4c-02fa9611d2bb.png)

**Comment by lmmrssa** [comment] 2020-03-19 15:17
Duplicate of  #5992

**Closed by lmmrssa** 2020-03-19 15:17 UTC
