### ISSUE TITLE
myHealth: examination taken by Health Provider should be mentioned somewhere

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6455] opened 2020-06-02 02:32 UTC
right now, Health Provider can also take examination of any member.
When member login with their credential, they can see examination added by Health Provider.
But no mention is given there such as who recorded the examination entry for that member.

Should Health Provider name should be shown to the Examination list for better clarification to members?
![Screenshot_2020-06-02 Planet Learning](https://user-images.githubusercontent.com/27276132/83473523-7fdf7280-a4a9-11ea-9bab-46b043ae2d8c.png)

**Comment by lmmrssa** [comment] 2020-06-11 16:17
Duplicate of #6515

**Closed** 2020-06-25 16:29 UTC
