### ISSUE TITLE
Can user wtih role admin/manager edit the achievement of user with role manager or learner or admin

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3214] opened 2019-02-20 01:42 UTC
also View Achievement button is not shown for user with role Learner in member Profile.
![screenshot from 2019-02-20 07-24-40](https://user-images.githubusercontent.com/27276132/53059994-fc328a00-34e0-11e9-89c7-aabc232fbe85.png)

**Comment by paulbert** [comment] 2019-02-20 03:09
Only allowing members to update their own achievements was intended, so I will close this issue

**Closed by paulbert** 2019-02-20 03:09 UTC
Labels: question
