### ISSUE TITLE
Resource/course: collection/subcollection listing error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4563] opened 2019-08-13 03:02 UTC
- Created a new Resource.
- Created new collection "three" and its subcollection "three-1"
![Screenshot from 2019-08-13 08-39-13](https://user-images.githubusercontent.com/27276132/62912124-824fcf00-bda6-11e9-8f4e-478e3763ac64.png)
- this collection and subcollection is automatically checked so when we hover around it, shows both "three" and "three-1"
![Screenshot from 2019-08-13 08-39-26](https://user-images.githubusercontent.com/27276132/62912153-9eec0700-bda6-11e9-8343-c91c167b2f8a.png)
- and this collection is also shown in resource list
- Created another resoources "new new" and selected "three-1" as only subcollection can be selected.

Problem:
- this collection didn't get updated to the list.
![Screenshot from 2019-08-13 08-42-10](https://user-images.githubusercontent.com/27276132/62912201-d35fc300-bda6-11e9-8f08-39e28879d0bb.png)
- on going to detail page of resource "new new" only subcollection is shown
![Screenshot from 2019-08-13 08-41-56](https://user-images.githubusercontent.com/27276132/62912215-e83c5680-bda6-11e9-934a-f2641ff4ae20.png)

**Comment by paulbert** [comment] 2019-08-13 03:52
Duplicate of #4529

**Closed by paulbert** 2019-08-13 03:52 UTC
