### ISSUE TITLE
Redirecting to Community result in console error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5616] opened 2020-01-23 15:21 UTC
going to Community page or redirecting to it shows console error.
I am not sure whether this console error shown on my machine only.
![Screenshot from 2020-01-23 21-03-47](https://user-images.githubusercontent.com/27276132/72997283-39577880-3e24-11ea-93d3-bbdcc2678381.png)

**Comment by paulbert** [comment] 2020-01-23 16:24
The issue is the bad urls in the news posts, which is a duplicate of #5583

**Closed by paulbert** 2020-01-23 16:24 UTC
