### ISSUE TITLE
When course added it is replacing old course

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3644] opened 2019-04-18 14:24 UTC
When new course is added it seem to replace old course.
![Screen Shot 2019-04-18 at 20 06 21](https://user-images.githubusercontent.com/2909490/56367796-c88c8b80-6215-11e9-984a-c46583346826.png)
![Screen Shot 2019-04-18 at 20 07 41](https://user-images.githubusercontent.com/2909490/56367798-c9252200-6215-11e9-8031-530bda2bfac0.png)

NOTE: adding course 4-5 time i was able to create new course once. other time it was replacing old course.

**Comment by lmmrssa** [comment] 2019-04-18 14:24
@paulbert is #3637 same issue?

**Comment by paulbert** [comment] 2019-04-18 14:34
Yes, duplicate of #3637 and also will likely be fixed in #3642.  I'm going to close this since I'm actively working on it.

**Closed by paulbert** 2019-04-18 14:34 UTC
Labels: bug
